### ISSUE TITLE
Wigner FFT + IFFT is not the identity for 'DH' sampling and low bandwidths

### ISSUE THREAD

**Issue by PhilippMisofCH** [astro-informatics/s2fft#242]
First of all, thanks again for this nice library. While working with it, I've noticed some unexpected results in my project, which eventually boil down to the fact that applying the inverse Wigner FFT on the Wigner FFT does not yield the original input, not even at low bandwidth (`L=8`) and `dh` sampling (This is actually one of the only cases that I've tested thoroughly). In contrast, an equivalent setup for the $S^2$ transforms seems to work as expected.

So I wondered if this is indeed a problem, or it is to be expected.

I've also attached a small example where I test this out:

```python
L = 8
sampling = 'dh'
a = s2fft.sampling.s2_samples.phis_equiang(L, sampling=sampling)
b = s2fft.sampling.s2_samples.thetas(L, sampling=sampling)
g = s2fft.sampling.s2_samples.phis_equiang(L, sampling=sampling)
f_grid = jnp.meshgrid(g, b, a, sparse=True, indexing='ij')
f_s2 = jnp.squeeze(jnp.sin(f_grid[1]) * jnp.cos(f_grid[2]))
flm = s2fft.transforms.spherical.forward_jax(f_s2, L, sampling=sampling, reality=True)
f_s2_back = s2fft.transforms.spherical.inverse_jax(flm, L, sampling=sampling)
assert jnp.allclose(f_s2, f_s2_back, atol=1e-4), ("Spherical forward + inverse transform is"
                                                  " not the identity")
                                                                                             
f_so3 = jnp.sin(f_grid[0]) * jnp.cos(f_grid[1]) * jnp.sin(f_grid[2])
flmn = s2fft.transforms.wigner.forward_jax(f_so3, L, L, sampling=sampling, reality=True)
f_back = s2fft.transforms.wigner.inverse_jax(flmn, L, L, sampling=sampling)
assert jnp.allclose(f_so3, f_back, atol=1e-2), ("Wigner forward + inverse transform is not "
                                                "the identity")
```
The first assertion passes, but the second one fails.

I've also looked around at other reported issues and found e.g.

- #209, but this seems to only appear for higher values of `N` than I'm testing here
- https://github.com/astro-informatics/s2fft/pull/170#issuecomment-1831649757 but this is specific to the HEALPix as far as I understand.

It would be great if you could tell me if I misunderstood something or if this is indeed a bug / numerical issue. Thanks in advance!

**Comment by CosmoMatt** [comment]
Hey @PhilippMisofCH so one of the assumptions of spherical harmonic (and by extension Wigner) transforms is that the underlying signals are band-limited (see e.g. section IV.A of this [paper](https://arxiv.org/pdf/1110.6298)). For signals that are not band-limited the truncation of the summation in equation 9 doesn't hold with equality.

### Generally
When you generate a random signal in pixel space it isn't necessarily band-limited, and therefore the (on its face reasonable) assumption that forward followed by inverse should return the original signal doesn't hold.

### Specifically
The checkerboard example you use here is a bit of a trick problem I think.

- For the spherical harmonic transform you use $f(\theta, \phi) = \sin\theta \cos\phi$. As $\theta \rightarrow 0$ the effective band-limit (maximum frequency) in $\phi \rightarrow 0$, which you can see by considering the case where $\theta = 0$ the function must necessarily be the same $\forall \phi$ as these are all the same locations on the sphere. What is making this function appear to work in the example is that $\sin\theta \rightarrow 0$ as $\theta \rightarrow 0$ and therefore $f(\theta,\phi) \rightarrow 0$ $\forall\phi$ which more closely satisfies (but by no means exactly) the effective band-limit in $\phi$ (everything is just 0). If you instead used $\cos\theta$ in $f(\theta,\phi)$ you will see much more substantial errors at both poles due to this.

- For the Wigner transform you use $f(\alpha, \beta,\gamma) = \sin\alpha\cos\beta\sin\gamma$. As per the above argument as $\beta\rightarrow0$ the $\cos\beta$ component doesn't kill the $\gamma$ and $\alpha$ dependencies, and therefore the signal fails to satisfy the effective band-limiting. Changing $\cos\beta$ to $\sin\beta$ reduces these errors somewhat, again for the reasons outlined above, but this is really just hiding the underlying band-limiting issue. If you explicitly band limit your function by <img width="791" alt="image" src="https://github.com/user-attachments/assets/18fe1131-21fc-4d28-a10a-148bf289277b"> you will find machine precision (or at least that's what I find on my side).

### Sidenote
As you mention, if you increase $N$ beyond $\sim 8$ or so you will start to see errors being introduced by the recursion. We've recently implemented [more stable recursions](https://github.com/astro-informatics/s2fft/blob/main/s2fft/recursions/risbo_jax.py) for these cases which you can pick up easily through the precompute [versions](https://github.com/astro-informatics/s2fft/blob/909e6f11c6b29ffcdaef6c5e055a3bc57addf297/s2fft/precompute_transforms/construct.py#L474) of these transforms. These should be stable $\forall N \leq L$, as always if you have any issues picking this functionality up let us know  :)

**Comment by PhilippMisofCH** [comment]
Thanks a lot for your detailed explanation! Your analysis of my particular example is spot on, I did not notice that.

I think one of my mistakes is that I assumed a signal generated on a *DH* grid is effectively band limited and we could still accurately reconstruct the signal at those points, though the signals would deviate quite a bit if compared at other points than the original grid.
My motivation for this was supported by the following working example in the 2d case, where I don't explicitly generate a signal out of a Fourier representation with a corresponding band limit:

```python
L = 8
rng = jax.random.PRNGKey(1234)
f_2d = jax.random.normal(rng, (L, L))
flm = jnp.fft.fft2(f_2d)
f_2d_back = jnp.fft.ifft2(flm)
assert jnp.allclose(f_2d, f_2d_back, atol=1e-8), ("2D fast Fourier + inverse transform is not the identity")
```
But I assume the actual problem is that I just don't fully understand the sampling theorems on a sphere yet, which is of course not relevant for a Github issue, so since you confirm that the original example works as expected, I'd consider this issue as resolved.

Regarding your sidenote: That is indeed useful to me, I will have a look at it!
